Arithmetic Exception
package Sampledemo;

public class Sample {

	public static void main(String[] args) {
	int num1=5;
	int num2=0;
	try {
		int num3=num1/num2;
		System.out.println(num3);
	}
	catch(ArithmeticException e) {
		System.out.println("Zero division error");
	}
	System.out.println("Program continues");

	}

}

Exception handling for Age

package Sampledemo;

public class Sample {

	public static void main(String[] args) {
	int age=15;

	try {
		if(age>=18) {
			System.out.println("Eligible to vote");
			
		}else {
			System.out.println("Not eligible to vote");
		}
	}
	
	
	catch(Exception e) {
		System.out.println("Error occured");
	}
	finally{
	System.out.println("Program continues");

	}
	

}
}
